config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  devise_for :users

  resources :identifies, only:[:new, :create]
  resources :specializations, only:[:new, :create]
  resources :personaldocs, only:[:new, :create]
  resources :educations, only:[:new, :create]
  resources :unifiedexams, only:[:new, :create]
  resources :educationforms, only:[:new, :create]
  resources :priorities, only:[:new, :create]
  resources :users, only:[:show] do 
      member do
          get :generatedocs
      end
  end

  root 'static_pages#home'

end

app/controllers/educationforms_controller.rb
class EducationformsController < ApplicationController

def create
  	puts(params)
  
  @doc = current_user.build_educationform(doc_params());

    if(@doc.save!)
      redirect_to new_educationform_path 
    else
      respond_to do |format|
        format.html {render 'new'}
        format.json { render :json => {errors: @doc.errors.full_messages} }
      end
    end
  end

  def new
  	@doc = current_user.build_educationform
    @doc.build_financingform
  end

protected
  def doc_params
    params.require(:educationform).permit(:state, financingform_attributes:[:id, :budget, :paid, :paid_budg ]);
  end

end

app/helpers/educationforms_helper.rb
module EducationformsHelper
end

app/views/educationforms/new.html.erb
<div class="row">
<div class="col-md-offset-4 col-md-4">
<%= simple_form_for @doc do |f| %>
	<%= f.input :state, collection: Educationform.states.keys, label: "Форма обучения"%>
	  <%= f.simple_fields_for :financingform do |p| %>
      <%= p.input :budget, as: :boolean, label: "Бюджет" %>
      <%= p.input :paid, as: :boolean, label: "Платное" %>
      <%= p.input :paid_budg, as: :boolean, label: "Контракт" %>
    <% end %>
    <%= f.button :submit, "Сохранить" %>
<% end %>
<%= button_to "Далее",  new_priority_path, :class => "btn btn-default btn-lg", :method => :get %>
</div>
</div>