config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  devise_for :users

  resources :identifies, only:[:new, :create]
  resources :specializations, only:[:new, :create]
  resources :personaldocs, only:[:new, :create]
  resources :educations, only:[:new, :create]
  resources :unifiedexams, only:[:new, :create]
  resources :educationforms, only:[:new, :create]
  resources :priorities, only:[:new, :create]
  resources :users, only:[:show] do 
      member do
          get :generatedocs
      end
  end

  root 'static_pages#home'

end

app/models/chair.rb
class Chair < ActiveRecord::Base
	has_many :specializations
end

app/models/education.rb
class Education < ActiveRecord::Base
	belongs_to :etype
	has_one :user
end

app/models/educationform.rb
class Educationform < ActiveRecord::Base
    enum state: [:full_time, :correspondence, :short_time]
	has_one :financingform
    accepts_nested_attributes_for :financingform

 	has_many :user


end

app/models/etype.rb
class Etype < ActiveRecord::Base
end

app/models/financingform.rb
class Financingform < ActiveRecord::Base
	belongs_to :educationform
end

app/models/gender.rb
class Gender < ActiveRecord::Base

	def to_label
		gender_title
	end
end

app/models/identify.rb
class Identify < ActiveRecord::Base
	belongs_to :type
	has_one :user
end

app/models/national.rb
class National < ActiveRecord::Base
end

app/models/personaldoc.rb
class Personaldoc < ActiveRecord::Base
	belongs_to :gender
	has_one :user
end

app/models/priority.rb
class Priority < ActiveRecord::Base
	belongs_to :specialization
	has_one :user
	def to_label
		Specialization.title
	end
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
	belongs_to :chair
	has_one :priority
end

app/models/type.rb
class Type < ActiveRecord::Base

	def to_label
		type_title
	end
end

app/models/unifiedexam.rb
class Unifiedexam < ActiveRecord::Base
	has_one :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :identify
  belongs_to :personaldoc
  belongs_to :education
  belongs_to :unifiedexam
  belongs_to :educationform
  belongs_to :priority

  def generatedocs
  	##puts "hello AMAZING PEOPLES!"
  	book = Spreadsheet.open "#{Rails.root}/templatebakalavriat.xls"
	sheet = book.worksheet 0
	sheet.each do |row|
		sheet.rows[4][6] = "#{self.personaldoc.first_name}"
		sheet.rows[5][6] = "#{self.personaldoc.second_name}"
		sheet.rows[6][6] = "#{self.personaldoc.third_name}"
		sheet.rows[7][7] = "#{self.identify.birthday}"
		sheet.rows[4][31] = "#{self.identify.country}"
		sheet.rows[5][45] = "#{self.identify.type_id}"
		sheet.rows[6][38] = "#{self.identify.series}"
		sheet.rows[6][45] = "#{self.identify.number}"
		sheet.rows[7][29] = "#{self.identify.issued_by}"
		sheet.rows[8][8] = "#{self.identify.birth_place}"
		sheet.rows[10][15] = "#{self.identify.address}"
		sheet.rows[11][37] = "#{self.personaldoc.phone_number}"
		sheet.rows[16][20] = "#{self.priority.first}"
		sheet.rows[18][20] = "#{self.priority.second}"
		sheet.rows[20][20] = "#{self.priority.third}"	
		sheet.rows[22][4] = "среднее (полное) общее образование"
		sheet.rows[27][0] = "Русский"
		sheet.rows[27][13] = "#{self.unifiedexam.russian}"
		sheet.rows[28][0] = "Математика"
		sheet.rows[28][13] = "#{self.unifiedexam.math}"
		sheet.rows[29][0] = "Физика"
		sheet.rows[29][13] = "#{self.unifiedexam.physics}"
		sheet.rows[30][0] = "Обществознание"
		sheet.rows[30][13] = "#{self.unifiedexam.social_science}"
		sheet.rows[33][22] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}" 
		sheet.rows[80][0] = DateTime.now.to_date
		sheet.rows[80][12] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}" 
		sheet.rows[27][26] = "Сертификат № #{self.unifiedexam.number}"
		sheet.rows[28][26] = "Сертификат № #{self.unifiedexam.number}" 
		sheet.rows[29][26] = "Сертификат № #{self.unifiedexam.number}" 
		sheet.rows[30][26] = "Сертификат № #{self.unifiedexam.number}" 
 
	end
	
	sheet1 = book.worksheet 1
	sheet1.each do |row|
		sheet1.rows[5][4] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}" 		
		sheet1.rows[9][24] = "#{self.priority.first}"
		sheet1.rows[21][24] = "#{self.priority.second}"
		sheet1.rows[33][24] = "#{self.priority.third}"
		sheet1.rows[12][36] = "14"
		sheet1.rows[46][1] = DateTime.now
		sheet1.rows[46][11] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}" 			
	end
	
	sheet2 = book.worksheet 2
	sheet2.each do |row|
		sheet2.rows[9][24] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}"
		sheet2.rows[17][5] = "№14 Ступинский филиал"
		sheet2.rows[130][4] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}"
		sheet2.rows[131][6] = "#{self.identify.address}"
		sheet2.rows[132][5] = "#{self.personaldoc.phone_number}"
		sheet2.rows[132][14] = "#{self.identify.birthday}"
		sheet2.rows[132][26] = "#{self.identify.series} #{self.identify.number}"
		sheet2.rows[133][7] = "#{self.identify.issued_by} #{self.identify.where}"
		sheet2.rows[138][19] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}"
		sheet2.rows[145][12] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}"
		sheet2.rows[145][27] = DateTime.now	
	end	

	sheet3 = book.worksheet 3
	sheet3.each do |row|
		sheet3.rows[4][6] = "#{self.personaldoc.first_name}"
		sheet3.rows[4][19] = "#{self.personaldoc.second_name}"
		sheet3.rows[4][35] = "#{self.personaldoc.third_name}"
		sheet3.rows[6][10] = "#{self.identify.birthday}"
		sheet3.rows[8][10] = "#{self.identify.birth_place}"
		sheet3.rows[10][8] = "#{self.identify.country}"
		sheet3.rows[14][1] = "#{self.education.university} #{self.education.where}"
		sheet3.rows[11][37] = "#{self.identify.address}"
		sheet3.rows[16][35] = "#{self.personaldoc.phone_number}"
		sheet3.rows[18][36] = DateTime.now
	end

	sheet4 = book.worksheet 4
	sheet4.each do |row|
		sheet4.rows[5][19] = "№14 Ступинский филиал"
		sheet4.rows[9][11] = "#{self.personaldoc.first_name}"
		sheet4.rows[10][11] = "#{self.personaldoc.second_name}"
		sheet4.rows[11][11] = "#{self.personaldoc.third_name}"
		sheet4.rows[12][11] = "#{self.identify.birthday}"
		sheet4.rows[13][11] = "#{self.identify.country}"
		sheet4.rows[9][32] = "среднее (полное) общее образование"
		sheet4.rows[12][31] = "#{self.identify.address}"
		sheet4.rows[9][11] = "#{self.personaldoc.first_name}"
		sheet4.rows[15][34] = "#{self.personaldoc.phone_number}"
		sheet4.rows[4][61] = "#{self.unifiedexam.math}"
		sheet4.rows[5][61] = "#{self.unifiedexam.russian}"
		sheet4.rows[6][61] = "#{self.unifiedexam.physics}"
		sheet4.rows[7][61] = "#{self.unifiedexam.social_science}"
		sheet4.rows[6][19] = "#{self.priority.first}"
	end

	sheet5 = book.worksheet 5
	sheet5.each do |row|
		sheet5.rows[6][7] = "#{self.personaldoc.first_name}"
		sheet5.rows[7][7] = "#{self.personaldoc.second_name}"
		sheet5.rows[8][7] = "#{self.personaldoc.third_name}"
		sheet5.rows[13][11] = DateTime.now
		sheet5.rows[5][8] = "#{self.priority.first}"
	end

	sheet6 = book.worksheet 6
	sheet6.each do |row|
		sheet6.rows[5][4] = "#{self.personaldoc.first_name} #{self.personaldoc.second_name} #{self.personaldoc.third_name}"
		sheet6.rows[9][2] = DateTime.now 
	end
	doclink = "#{Rails.root}/public/xlsdocs/#{Time.now.strftime("%y%m%d_%3s")}_#{self.personaldoc.first_name}_#{self.personaldoc.second_name}.xls"
	book.write doclink
	doclink
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :is_admin, only:[:generatedocs]

  def show
  	@user = User.find(params[:id]);
  end

  def generatedocs
  	@user = User.find(params[:id])
  	send_file @user.generatedocs
  end
  
  protected
  	def is_admin
  		unless current_user.admin?
  			flash[:error]="error!"
  			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/identifies_helper.rb
module IdentifiesHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/priorities_helper.rb
module PrioritiesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/unifiedexam_helper.rb
module UnifiedexamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_showforadmin.html.erb
<div class="row">
<div class="col-md-offset-4 col-md-4">
<% if current_user.admin? %>
	<list>
	<%User.all.each do |x| %>
		<li><%= link_to "#{x.personaldoc.first_name} #{x.personaldoc.second_name} #{x.personaldoc.third_name}",  generatedocs_user_path(x) %></li>
	<%end%>
	</list>
<%end%>
</div>
</div>

app/views/users/_showforuser.html.erb
<div class="row">
<div class="col-md-offset-4 col-md-4">
<% if signed_in? %>
	<list>
		<h4>Удостоверение личности </h4>
		<li><b>Оригинал:</b><%= " #{@user.identify.original}" %></li>
		<li><b>Тип удостоверения личности:</b> <%= " #{@user.identify.type.type_title}" %></li>
		<li><b>Страна:</b><%= " #{@user.identify.country}" %></li>
		<li><b>Серия:</b><%= " #{@user.identify.series}" %></li>
		<li><b>Номер:</b><%= " #{@user.identify.number}" %></li>
		<li><b>Подразделение:</b><%= " #{@user.identify.unit}" %></li>
		<li><b>Когда:</b><%= " #{@user.identify.where}" %></li>
		<li><b>Кем выдан:</b><%= " #{@user.identify.issued_by}" %></li>
		<li><b>Дата рождения:</b><%= " #{@user.identify.birthday}" %></li>
		<li><b>Место рождения:</b><%= " #{@user.identify.birth_place}" %></li>
		<li><b>Адрес:</b><%= " #{@user.identify.address}" %></li>
	</list>
	<br>
	<list>
		<h4>Персональные данные </h4>
		<li><b>Фамилия:</b><%= " #{@user.personaldoc.first_name}" %></li>
		<li><b>Имя:</b><%= " #{@user.personaldoc.second_name}" %></li>
		<li><b>Отчество:</b><%= " #{@user.personaldoc.third_name}" %></li>
		<li><b>Пол:</b><%= " #{@user.personaldoc.gender.gender_title}" %></li>
		<li><b>Специальные права:</b><%= " #{@user.personaldoc.special_rights}" %></li>
		<li><b>Сп_возврата:</b><%= " #{@user.personaldoc.сп_возврата}" %></li>
	</list>
	<br>
	<list>
		<h4>Образовательный документ </h4>
		<li><b>Оригинал:</b><%= " #{@user.education.original}" %></li>
		<li><b>Серия:</b><%= " #{@user.education.series}" %></li>
		<li><b>Номер:</b><%= " #{@user.education.number}" %></li>
		<li><b>Когда:</b><%= " #{@user.education.where}" %></li>
		<li><b>ВУЗ:</b><%= " #{@user.education.university}" %></li>
		<li><b>Тип образовательного документа:</b><%= " #{@user.education.etype.title}" %></li>
	</list>
	<br>
	<list>
		<h4>Результаты ЕГЭ </h4>
		<li><b>Оригинал:</b><%= " #{@user.unifiedexam.original}" %></li>
		<li><b>Год:</b><%= " #{@user.unifiedexam.year}" %></li>
		<li><b>Номер:</b><%= " #{@user.unifiedexam.number}" %></li>
		<li><b>Русский:</b><%= " #{@user.unifiedexam.russian}" %></li>
		<li><b>Математика:</b><%= " #{@user.unifiedexam.math}" %></li>
		<li><b>Физика:</b><%= " #{@user.unifiedexam.physics}" %></li>
		<li><b>Обществознание:</b><%= " #{@user.unifiedexam.social_science}" %></li>
	</list>
	<br>
	<list>
		<h4>Форма обучения и финансирования</h4>
		<li><b>Форма обучения:</b><%= " #{@user.educationform.state}" %></li>
	</list>
	<br>
	<list>
		<h4>Приоритет специальностей</h4>
		<li><b>1:</b><%= " #{@user.priority.first}" %></li>
		<li><b>2:</b><%= " #{@user.priority.second}" %></li>
		<li><b>3:</b><%= " #{@user.priority.third}" %></li>
	</list>
<%end%>
</div>
</div>

app/views/users/_showforuserwithoutdocs.html.erb
<div class="row">
<div class="col-md-offset-4 col-md-4">
<p> Нажмите на кнопку для заполнения документов </p>
<%= link_to "Заполнить анкету", new_identify_path, class:"btn btn-primary" %>
</div>
</div>

app/views/users/show.html.erb
<% if current_user.admin? %>
	<%= render 'showforadmin' %>
<% else %>
	<% if current_user.identify_id.nil? %>
		<%= render 'showforuserwithoutdocs' %>
	<% else %>
		<%= render 'showforuser' %>
	<% end %>	
<% end %>